### ISSUE TITLE
How to run?

### ISSUE THREAD

**Issue by bartvanderwal** [jaspervz/todo-http4s-doobie#1]
Hi @jaspervz ; I just saw your post about this on LinkedIn and was interested. Nice work!

No front end is included for your API in order to try it out. That wouldn't fit the microservices approach, so I get that.

## Question
But could you describe - in the README.md - an example how to test this? For instance how to make a JSON post request to add a todo. Since at the start it seems empty, there are no test todo's; e.g. I get `[]` back from `/todos`. Or you could seed the H2 database to have test data. 

Or perhaps there is something wrong with running h2? I'm not familiar with this, how can I test this separately?

## My attempts
I tried to add a todo with a POST request via [POSTman](https://www.getpostman.com/) as you can see in the following screenshot. After some trial and error I didn't get an error back anymore, but still it seems like no todo was added. Or is there still a bug? Or is the 

![todo-http4s-doobie](https://user-images.githubusercontent.com/3029472/34625968-18bc7286-f25b-11e7-8fd1-8f206adadeda.png)

**Comment by jaspervz** [comment]
Hello @bartvanderwal . Thank you for your feedback. I added examples to the readme on how to use the microservice with curl.
 
The reason why your request failed it that the importance should be spelled lowercase, so High should be high.

**Comment by bartvanderwal** [comment]
Ok thanks for the quick response!

Indeed the API is case sensitive for the (probably) enum value. I could now add a todo by following your description in the README, via curl, or with postman:

![bug-todos-doobie-fixed](https://user-images.githubusercontent.com/3029472/34672146-95610d50-f47d-11e7-8549-63dcbbe1ef9f.png)
