### ISSUE TITLE
Use pureconfig-cats-effect

### ISSUE THREAD

**Issue by wogan** [jaspervz/todo-http4s-doobie#3]
The [cats-effect module](https://github.com/pureconfig/pureconfig/tree/master/modules/cats-effect) for PureConfig provides a `loadConfigF` function, which can replace most of the code in your `config` package object.

Great example project BTW 👍

**Comment by jaspervz** [comment]
A good suggestion, only the latest stable http4s version depends on an older version of cats effect, so until there is a release of http4s that depends on the latest cats-effect version, I unfortunately can't make the change yet.

**Comment by jaspervz** [comment]
The cats-effect module of PureConfig is now used.
